version: 3.9
services:
  Nodeapp:
    build: .
    container_name: travel-node-app
    ports:
      - "4001:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/travelEas
    depends_on:
      - Mongodb

  Mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

