apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-app
  labels:
    app: travel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-app
  template:
    metadata:
      labels:
        app: travel-app
    spec:
      containers:
        - name: travel-booking-app
          image: sreeja026/travel-app-image:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/travelEas"
